# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pfc_marker_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(570, 220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(570, 220))
        MainWindow.setMaximumSize(QtCore.QSize(570, 220))
        MainWindow.setBaseSize(QtCore.QSize(60, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pfc_marker_logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setIconSize(QtCore.QSize(512, 512))
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setEnabled(True)
        self.logo.setGeometry(QtCore.QRect(-15, 55, 122, 122))
        self.logo.setMinimumSize(QtCore.QSize(122, 122))
        self.logo.setMaximumSize(QtCore.QSize(122, 122))
        self.logo.setMouseTracking(False)
        self.logo.setToolTip("")
        self.logo.setStatusTip("")
        self.logo.setAutoFillBackground(False)
        self.logo.setLineWidth(0)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/pfc_marker_logo.svg"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setWordWrap(False)
        self.logo.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logo.setObjectName("logo")
        self.btn_import = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import.setGeometry(QtCore.QRect(480, 20, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_import.sizePolicy().hasHeightForWidth())
        self.btn_import.setSizePolicy(sizePolicy)
        self.btn_import.setMinimumSize(QtCore.QSize(80, 30))
        self.btn_import.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_import.setFont(font)
        self.btn_import.setToolTip("import markers into pfclean project")
        self.btn_import.setStatusTip("import markers into pfclean project")
        self.btn_import.setWhatsThis("")
        self.btn_import.setAccessibleName("")
        self.btn_import.setAutoDefault(False)
        self.btn_import.setDefault(False)
        self.btn_import.setFlat(False)
        self.btn_import.setObjectName("btn_import")
        self.combobox_selectseq = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_selectseq.setGeometry(QtCore.QRect(100, 21, 220, 28))
        self.combobox_selectseq.setMinimumSize(QtCore.QSize(220, 28))
        self.combobox_selectseq.setMaximumSize(QtCore.QSize(210, 28))
        self.combobox_selectseq.setToolTip("select a sequence")
        self.combobox_selectseq.setStatusTip("select a sequence")
        self.combobox_selectseq.setWhatsThis("")
        self.combobox_selectseq.setAccessibleName("")
        self.combobox_selectseq.setObjectName("combobox_selectseq")
        self.combobox_selectseq.addItem("")
        self.btn_seledl = QtWidgets.QPushButton(self.centralwidget)
        self.btn_seledl.setGeometry(QtCore.QRect(400, 20, 70, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_seledl.sizePolicy().hasHeightForWidth())
        self.btn_seledl.setSizePolicy(sizePolicy)
        self.btn_seledl.setMinimumSize(QtCore.QSize(70, 30))
        self.btn_seledl.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_seledl.setFont(font)
        self.btn_seledl.setToolTip("select cmx3600 edl")
        self.btn_seledl.setStatusTip("select cmx3600 edl")
        self.btn_seledl.setWhatsThis("")
        self.btn_seledl.setAccessibleName("")
        self.btn_seledl.setAutoDefault(False)
        self.btn_seledl.setDefault(False)
        self.btn_seledl.setFlat(False)
        self.btn_seledl.setObjectName("btn_seledl")
        self.btn_selprj = QtWidgets.QPushButton(self.centralwidget)
        self.btn_selprj.setGeometry(QtCore.QRect(10, 20, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_selprj.sizePolicy().hasHeightForWidth())
        self.btn_selprj.setSizePolicy(sizePolicy)
        self.btn_selprj.setMinimumSize(QtCore.QSize(80, 30))
        self.btn_selprj.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_selprj.setFont(font)
        self.btn_selprj.setToolTip("select pfclean-project-file")
        self.btn_selprj.setStatusTip("select pfclean-project-file")
        self.btn_selprj.setWhatsThis("")
        self.btn_selprj.setAccessibleName("")
        self.btn_selprj.setAutoDefault(False)
        self.btn_selprj.setDefault(False)
        self.btn_selprj.setFlat(False)
        self.btn_selprj.setObjectName("btn_selprj")
        self.btn_xml = QtWidgets.QPushButton(self.centralwidget)
        self.btn_xml.setEnabled(False)
        self.btn_xml.setGeometry(QtCore.QRect(480, 60, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_xml.sizePolicy().hasHeightForWidth())
        self.btn_xml.setSizePolicy(sizePolicy)
        self.btn_xml.setMinimumSize(QtCore.QSize(80, 30))
        self.btn_xml.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_xml.setFont(font)
        self.btn_xml.setToolTip("save xml formatted markers")
        self.btn_xml.setStatusTip("save xml formatted markers")
        self.btn_xml.setWhatsThis("")
        self.btn_xml.setAccessibleName("")
        self.btn_xml.setAutoDefault(False)
        self.btn_xml.setDefault(False)
        self.btn_xml.setFlat(False)
        self.btn_xml.setObjectName("btn_xml")
        self.btn_selcp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_selcp.setEnabled(False)
        self.btn_selcp.setGeometry(QtCore.QRect(400, 60, 70, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_selcp.sizePolicy().hasHeightForWidth())
        self.btn_selcp.setSizePolicy(sizePolicy)
        self.btn_selcp.setMinimumSize(QtCore.QSize(70, 30))
        self.btn_selcp.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_selcp.setFont(font)
        self.btn_selcp.setToolTip("select clipster project")
        self.btn_selcp.setStatusTip("select clipster project")
        self.btn_selcp.setWhatsThis("")
        self.btn_selcp.setAccessibleName("")
        self.btn_selcp.setAutoDefault(False)
        self.btn_selcp.setDefault(False)
        self.btn_selcp.setFlat(False)
        self.btn_selcp.setObjectName("btn_selcp")
        self.label_msgs = QtWidgets.QTextEdit(self.centralwidget)
        self.label_msgs.setGeometry(QtCore.QRect(100, 102, 368, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_msgs.sizePolicy().hasHeightForWidth())
        self.label_msgs.setSizePolicy(sizePolicy)
        self.label_msgs.setAutoFillBackground(False)
        self.label_msgs.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_msgs.setFrameShape(QtWidgets.QFrame.Box)
        self.label_msgs.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_msgs.setLineWidth(0)
        self.label_msgs.setMidLineWidth(0)
        self.label_msgs.setReadOnly(True)
        self.label_msgs.setObjectName("label_msgs")
        self.checkBox_srctc = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_srctc.setGeometry(QtCore.QRect(340, 20, 50, 17))
        self.checkBox_srctc.setToolTip("")
        self.checkBox_srctc.setStatusTip("")
        self.checkBox_srctc.setWhatsThis("")
        self.checkBox_srctc.setAccessibleName("")
        self.checkBox_srctc.setObjectName("checkBox_srctc")
        self.checkBox_rectc = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rectc.setGeometry(QtCore.QRect(340, 34, 50, 17))
        self.checkBox_rectc.setToolTip("")
        self.checkBox_rectc.setStatusTip("")
        self.checkBox_rectc.setWhatsThis("")
        self.checkBox_rectc.setChecked(True)
        self.checkBox_rectc.setObjectName("checkBox_rectc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuUpdate = QtWidgets.QMenu(self.menubar)
        self.menuUpdate.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.menuUpdate.setFont(font)
        self.menuUpdate.setAccessibleDescription("")
        self.menuUpdate.setTearOffEnabled(False)
        self.menuUpdate.setObjectName("menuUpdate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setEnabled(False)
        self.actionUpdate.setObjectName("actionUpdate")
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuUpdate.addAction(self.actionUpdate)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuUpdate.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pfc_marker"))
        self.btn_import.setText(_translate("MainWindow", "import"))
        self.combobox_selectseq.setItemText(0, _translate("MainWindow", "select sequence"))
        self.btn_seledl.setText(_translate("MainWindow", "select edl"))
        self.btn_selprj.setText(_translate("MainWindow", "select pfrp"))
        self.btn_xml.setText(_translate("MainWindow", "save xml"))
        self.btn_selcp.setText(_translate("MainWindow", "select cp"))
        self.checkBox_srctc.setText(_translate("MainWindow", "src tc"))
        self.checkBox_rectc.setText(_translate("MainWindow", "rec tc"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuUpdate.setTitle(_translate("MainWindow", "Update avialable!"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setIconText(_translate("MainWindow", "preferences"))
        self.actionPreferences.setToolTip(_translate("MainWindow", "preferences"))
        self.actionPreferences.setStatusTip(_translate("MainWindow", "preferences"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "exit application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "general info"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))
        self.actionUpdate.setStatusTip(_translate("MainWindow", "check for updates"))

import images_rc
